// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmcXpmBJLiWdWRlNKFfjqQ6MP6iVvs7Qw',
    appId: '1:468196748153:android:5453e198dd3f6ec8a79da8',
    messagingSenderId: '468196748153',
    projectId: 'chess-app-fdaec',
    storageBucket: 'chess-app-fdaec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYJL_0DiiocE6iELp9cZnTd5pLB6a4Ac',
    appId: '1:468196748153:ios:1e10882b326700d9a79da8',
    messagingSenderId: '468196748153',
    projectId: 'chess-app-fdaec',
    storageBucket: 'chess-app-fdaec.firebasestorage.app',
    iosBundleId: 'com.example.chessgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiYJL_0DiiocE6iELp9cZnTd5pLB6a4Ac',
    appId: '1:468196748153:ios:1e10882b326700d9a79da8',
    messagingSenderId: '468196748153',
    projectId: 'chess-app-fdaec',
    storageBucket: 'chess-app-fdaec.firebasestorage.app',
    iosBundleId: 'com.example.chessgame',
  );
}
